version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/express-api"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/svelte-app"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/sanity-cms"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
